### ISSUE TITLE
Collection of various small things

### ISSUE THREAD

**Issue by mProjectsCode** [TfTHacker/obsidian42-HelpMate#1]
- Forward and Backward navigation does not work with the OS hotkeys
- The system theme of the webview should be set to the theme selected in Obsidians settings (for dark and light)
- Commands to open specific docs would be nice
- The dropdown that opens when clicking on the webview settings should close on a click outside of the dropdown

**Comment by TfTHacker** [comment]
Great feedback. I am debating how far to take the embedded browser so as not to duplicate a real browser.

I love the idea of commands to open specific docs. Then they could also be mapped to shortcut keys.

Any chance of getting you to add helpUrl to the manifest of your plugins?

**Comment by TfTHacker** [comment]
One other thing, i dont think I can force the site to be in dark mode, since this is just an embedded browser. But many of the help sites, especially those that are obsidian publish sites can be configured in the navigation to be in dark mode. This setting does persist in HelpMate.

**Comment by mProjectsCode** [comment]
> One other thing, i dont think I can force the site to be in dark mode, since this is just an embedded browser. But many of the help sites, especially those that are obsidian publish sites can be configured in the navigation to be in dark mode. This setting does persist in HelpMate.

The thing i meant was the [browser API](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to adapt the theme to the system theme. The meta bind docs should use that do adapt to your system theme. I thought that it might be possible to set the value the API returns to the website to the same as the theme in obsidian.

**Comment by mProjectsCode** [comment]
> Any chance of getting you to add helpUrl to the manifest of your plugins?

Already did that for meta bind, just haven't pushed it yet. My other plugins are a bit lacking on the docs side of things 😅.

**Comment by TfTHacker** [comment]
> > Any chance of getting you to add helpUrl to the manifest of your plugins?
> 
> Already did that for meta bind, just haven't pushed it yet. My other plugins are a bit lacking on the docs side of things 😅.

Awesome. I just added Command Palette support as you recommended, which is great, now we can link hotkeys for quickly hopping into help at a specific point.

**Comment by TfTHacker** [comment]
I stand corrected, at least on the desktop electron supports the system light/dark mode flag. Though its based on the system, not on Obsidian. but at least its a step closer.

**Comment by TfTHacker** [comment]
Sorry for all the spam. I think I will hold off on implementing back and forth buttons, just to see if I get more feedback on that idea.

System adapting to dark/light mode coming in upcoming release.
