### ISSUE TITLE
HelpMate Help returns 404 Not found

### ISSUE THREAD

**Issue by I-Pch** [TfTHacker/obsidian42-HelpMate#2]
Hi there 😊 !

I've installed HelpMate through BRAT on Obsidian Mobile (iPad) and it works great 😁 ! (Thanks for building such a useful plugin btw 🙌 )

I didn't change any settings and didn't add any "custom help resources" either and while exploring the help documentation available through the plugin I discovered that:

Selecting `HelpMate Help` in the `Bookmarks` dropdown leads to 404 - Page not found error ...

![HelpMate Help - 404](https://github.com/TfTHacker/obsidian42-HelpMate/assets/77828085/2489e4c3-1b6d-4a27-bbe8-1db992f11aa5)

But, selecting `Obsidian42 - HelpMate` actually leads to the concerned help page 😊 .

![Obsidian42 - HelpMate](https://github.com/TfTHacker/obsidian42-HelpMate/assets/77828085/c0f98e74-7045-4165-83d5-0b3569fa277c)

Both `HelpMate Help` and `Obsidian42 - HelpMate` seem to be tied to the same link though... 
It's just that `HelpMate Help` leads to https://tfthacker.com/helpmate whereas `Obsidian42 - HelpMate` leads to https://tfthacker.com/HelpMate so I can only guess, it's a case sensitivity thing 😇.

It's just a detail but I thought I'd mentioned it 😊 !

Thank you so very much for creating and sharing this plugin again 🙌 !

**Comment by TfTHacker** [comment]
Wow, embarrassing baggage from my testing 🤓. I will fix this and thank you for reporting it. It took your time, and I appreciate it! This will be fixed in an update I push out later today.
