### ISSUE TITLE
Suggestion: Default Help Site

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [TfTHacker/obsidian42-HelpMate#5]
I would really like to be able to set a Default Help Site. 
I publish a vault and being able to link it to default to my Publish Site would be very useful.

**Comment by TfTHacker** [comment]
Hello and thank you for reaching out to me,

This is possible already, though not readily apparent. In settings, you can set the "Obsidian Help" url to any URL you want, and this is the default load page.

Then just move the Obsidian Help link that is in that default field into the custom settings below.

<img width="794" alt="image" src="https://github.com/TfTHacker/obsidian42-HelpMate/assets/69121180/12d6b060-6f5d-49e4-b44b-8b1c382e990d">
